### ISSUE TITLE
Any plan to work in React Native?

### ISSUE THREAD

**Issue by jiyinyiyong** [andrewdavey/immutable-devtools#26]
Tried but got an error before running the code:
```text
[node-haste] Encountered an error while persisting cache:
> SyntaxError: /Users/chen/repo/gist/Todolist/node_modules/immutable-devtools/before.png: Unexpected character '�' (1:0)
> > 1 | �PNG
>     | ^
>   2 | 
>   3 | 
>   4 | IHDR����
                EiCCPICC ProfileH
>     at Parser.pp.raise (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/parser/location.js:22:13)
>     at Parser.getTokenFromCode (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/tokenizer/index.js:561:12)
>     at Parser.readToken (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/tokenizer/index.js:180:21)
>     at Parser.<anonymous> (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/plugins/jsx/index.js:51:20)
>     at Parser.readToken (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/plugins/flow.js:155:22)
>     at Parser.nextToken (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/tokenizer/index.js:169:21)
>     at Parser.parse (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/parser/index.js:128:12)
>     at parse (/Users/chen/repo/gist/Todolist/node_modules/babylon/lib/index.js:47:47)
>     at File.parse (/Users/chen/repo/gist/Todolist/node_modules/babel-core/lib/transformation/file/index.js:517:34)
>     at File.parseCode (/Users/chen/repo/gist/Todolist/node_modules/babel-core/lib/transformation/file/index.js:603:20)
```

**Comment by langpavel** [comment]
Why image used only in documentation is parsed by tooling? Also this tool works only in Google Chrome console..

**Comment by jiyinyiyong** [comment]
@langpavel React Native does use Chrome Devtools as React does https://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools

So the image is only in docs, also looks strange to me.

**Comment by langpavel** [comment]
Hmm, I'm not sure how to fix this...

**Comment by jiyinyiyong** [comment]
I removed the images(as an experiment) and it stopped throwing errors. It does not work too. So React Native is running in a worker, maybe the separation of contexts breaks this module.
![image](https://cloud.githubusercontent.com/assets/449224/15706665/5600f9aa-2827-11e6-9061-24cb1b5a3828.png)

**Comment by langpavel** [comment]
support for `window.devtoolsFormatters` API is very vague. This can be issue too...
